apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricepointscout
  namespace: pps-namespace
spec:
  selector:
    matchLabels:
      app: pricepointscout
  template:
    metadata:
      labels:
        app: pricepointscout
    spec:
      containers:
      - name: pricepointscout
        image: omarzakaria10/price-point-scout:4176f77fe81a23c3f27a185750700c01b67a54d4
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          limits:
            cpu: "1.5"
            memory: "3Gi"
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: pps-configmap
        - secretRef:
            name: pricepointscout-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: pricepointscout-service
  namespace: pps-namespace
spec:
  selector:
    app: pricepointscout
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
